### ISSUE TITLE
跳转 kimi 并附带已有讨论的实现方式

### ISSUE THREAD

**Issue by loveQt** [careywyr/trans-agent#1]
路过看到这个项目，感觉想法和苏神的 papers.cool 有点像 https://github.com/bojone/papers.cool
顺便分享一下 跳转 kimi 并附带已有讨论的实现方式吧：

通过补全以下链接可以跳转至 Kimi 网页版：
http://kimi.moonshot.cn/_prefill_chat?prefill_prompt={prompt}&send_immediately=true&force_search=false

在 papers.cool 中的 Prompt 模板是：
`我们要讨论的论文是{}，链接是 {} ，已有的FAQ链接是 {} 。请以此为基础，继续回答我后面的问题。`

希望对你的后续实现有所帮助。

**Comment by careywyr** [comment]
其实跳转kimi这个我也是看的苏神的这个网站才知道可以这么玩的，但我还再思考本地化部署的时候FAQ怎么给比较好，因为他这个是线上的，所以可以直接给链接，如果本地的可能只能给文本了。

我这个更倾向于本地化部署以及跟自己的笔记能关联，包括LLM除了使用云端的后面考虑支持本地ollama，但现在都还在规划设计。目前论文阅读主要是使用zotero+obsidian结合，论文多了感觉还是很难找笔记以及归纳总结，需要一个工具提升一些效率，就突发奇想写一个。

还是很感谢你的建议！🙂
